In [2]:
from pathlib import Path
import warnings
warnings.filterwarnings("ignore")

DATA_DIR = Path("./files")
if not DATA_DIR.exists():
    DATA_DIR = Path("./files")

print(f"데이터 폴더 : {DATA_DIR.resolve()}")

데이터 폴더 : C:\Users\Administrator\bigdata2026\bigdata2026-basic\새 폴더\files

In [3]:
import pandas as pd

df = pd.read_csv(DATA_DIR/"cafe_sales.csv")

In [4]:
df.head()

         date  temperature_c  promotion  weekend  foot_traffic  sales_10k_krw
0  2026-01-01           31.9          1        0           205          128.4
1  2026-01-02           17.6          0        0           151          120.6
2  2026-01-03           15.9          0        1           143          108.9
3  2026-01-04           25.4          1        1           169          127.7
4  2026-01-05           19.2          0        0           114           84.5

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           240 non-null    str
 1   temperature_c  240 non-null    float64
 2   promotion      240 non-null    int64
 3   weekend        240 non-null    int64
 4   foot_traffic   240 non-null    int64
 5   sales_10k_krw  240 non-null    float64
dtypes: float64(2), int64(3), str(1)
memory usage: 11.4 KB

In [6]:
df.describe()

       temperature_c   promotion     weekend  foot_traffic  sales_10k_krw
count     240.000000  240.000000  240.000000    240.000000     240.000000
mean       16.862500    0.545833    0.283333    155.200000     105.222917
std         7.567858    0.498935    0.451559     31.144716      17.909732
min        -5.000000    0.000000    0.000000     74.000000      59.500000
25%        11.875000    0.000000    0.000000    135.750000      92.450000
50%        16.550000    1.000000    0.000000    157.000000     105.750000
75%        21.900000    1.000000    1.000000    177.000000     117.825000
max        35.000000    1.000000    1.000000    229.000000     147.200000

In [8]:
df.describe(include="all")

,date,temperature_c,promotion,weekend,foot_traffic,sales_10k_krw
count,240,240.000000,240.000000,240.000000,240.000000,240.000000
unique,240,NaN,NaN,NaN,NaN,NaN
top,2026-01-01,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN
mean,NaN,16.862500,0.545833,0.283333,155.200000,105.222917
std,NaN,7.567858,0.498935,0.451559,31.144716,17.909732
min,NaN,-5.000000,0.000000,0.000000,74.000000,59.500000
25%,NaN,11.875000,0.000000,0.000000,135.750000,92.450000
50%,NaN,16.550000,1.000000,0.000000,157.000000,105.750000
75%,NaN,21.900000,1.000000,1.000000,177.000000,117.825000
max,NaN,35.000000,1.000000,1.000000,229.000000,147.200000

In [ ]:
df.describe(include="all").T # .T는 행/열 바꾸기

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
date,240,240,2026-01-01,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
temperature_c,240.0,NaN,NaN,NaN,16.8625,7.567858,-5.0,11.875,16.55,21.9,35.0
promotion,240.0,NaN,NaN,NaN,0.545833,0.498935,0.0,0.0,1.0,1.0,1.0
weekend,240.0,NaN,NaN,NaN,0.283333,0.451559,0.0,0.0,0.0,1.0,1.0
foot_traffic,240.0,NaN,NaN,NaN,155.2,31.144716,74.0,135.75,157.0,177.0,229.0
sales_10k_krw,240.0,NaN,NaN,NaN,105.222917,17.909732,59.5,92.45,105.75,117.825,147.2

### 입력(피처)과 정답(타겟)을 분리
- 입력(피처) --> X (주로 대문자 X)
- 정답(타겟) --> y (주로 소문자 y)

In [10]:
feature_cols = ["temperature_c", "promotion", "weekend", "foot_traffic"] # 입력(피처): 영향을 주는 것
target_col = "sales_10k_krw" # 정답(타겟): 알고 싶은 것

X = df[feature_cols]
y = df[target_col]

X.head()

   temperature_c  promotion  weekend  foot_traffic
0           31.9          1        0           205
1           17.6          0        0           151
2           15.9          0        1           143
3           25.4          1        1           169
4           19.2          0        0           114

In [11]:
y.head()

0    128.4
1    120.6
2    108.9
3    127.7
4     84.5
Name: sales_10k_krw, dtype: float64

In [12]:
X.shape, y.shape

((240, 4), (240,))

### 훈련 데이터와 검증 데이터 나누기
- 사이킷런 라이브러리 사용
- train_test_split() 함수 사용

In [13]:
from sklearn.model_selection import train_test_split

# 4개의 변수값이 결과로 나온다. (X, X, y, y) (홀수번째 학습용, 짝수번째 검증용(테스트용))
# 8:2 비율로 나눈다 --> 8 train, 2 valid
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.shape, X_valid.shape, y_train.shape, y_valid.shape

((192, 4), (48, 4), (192,), (48,))